### ISSUE TITLE
Fn for credentials?

### ISSUE THREAD

**Issue by pjt** [sharetribe/aws-sig4#2]
Greetings – thanks for the very useful library!

I'm interested in using temporary AWS credentials, which need to be refreshed on some interval. Would you consider a patch that changed the signature of `aws-sig4/build-wrap-aws-auth` to accept either a map, as it currently does, or a function which could handle credential refreshes as appropriate? The latter would allow for use of temporary credentials without having to create a new instance of the middleware per refresh.

**Comment by ovan** [comment]
Hi @pjt. I'm really happy to hear you found the lib useful. We are using temporary AWS credentials too. Our approach is to construct a middleware instance per request. I feel this keeps things simple. Are you worried about the overhead with this approach?

One option for handing this would be to wrap the middleware building:

```clojure
;; Build a configured middleware chain.
;; wrap with e.g. core.memoize (https://github.com/clojure/core.memoize) for caching with periodic refresh
(defn mw-chain ...)

(with-additional-middleware
  (mw-chain)
  ; send request

```

If the use case you have in mind can be served with something like this then I'd rather keep the function signature simple. If I missed something let me know and I'm happy reconsider.

Thanks for asking beforehand!

**Comment by pjt** [comment]
Thanks for the reply, @ovan. It hadn't occurred to me to construct the middleware per request, but I don't think that's unreasonable. I'll give that approach a try. Thanks again!
